name: ci-test

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  
  test:
    name: Test
    runs-on: ubuntu-latest
    # Service container: Postgres
    services: 
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: Computationalinguist
          POSTGRES_DB: simple_bank

        # check database setup
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out go in the go module directory
        uses: actions/checkout@v2

      - name: Migrate database
        run: make migrateup

      - name: Start CI Test
        run: make test

